env:
    OEM: realme
    CODENAME: RMX2020
    CIRRUS_CI: true
    CIRRUS_SHELL: bash
    TARGET: make bacon -j16
    ROM_NAME: lineage
    PRODUCT_NAME: lineage_RMX2020
    VARIANT: userdebug
    ROM_REPO: "https://github.com/LineageOS/android"
    ROM_BRANCH: lineage-18.1 --git-lfs
    DEVICE_REPO: "https://github.com/Realme-G70-Series/device_realme_RMX2020"
    DEVICE_BRANCH: lineage-18.1
    VENDOR_REPO: "https://github.com/Realme-G70-Series/vendor_realme_RMX2020"
    VENDOR_BRANCH: 11-rmui1
    KERNEL_REPO: "https://github.com/Realme-G70-Series/kernel_realme_RMX2020"
    KERNEL_BRANCH: Arrow-11.0
    USERNAME: satorugojo2k23
    USERMAIL: satorugojo4200@gmail.com
    OUTPUT: lineage_*.zip
    
task:
  name: "ROM Build"
  timeout_in: 240m
  trigger_type: manual
  container:
      image: ghcr.io/satorugojo2k23/ubuntu:latest
      cpu: 8
      memory: 32G
      
 # CLONE_SCRIPT_script: |
 #   if [ -z "$CIRRUS_PR" ]; then
 #     git clone --recursive --branch=$CIRRUS_BRANCH https://x-access-token:${CIRRUS_REPO_CLONE_TOKEN}@github.com/${CIRRUS_REPO_FULL_NAME}.git $CIRRUS_WORKING_DIR
  #    git reset --hard $CIRRUS_CHANGE_IN_REPO
  #  else
  #    git clone --recursive https://x-access-token:${CIRRUS_REPO_CLONE_TOKEN}@github.com/${CIRRUS_REPO_FULL_NAME}.git $CIRRUS_WORKING_DIR
  #    git fetch origin pull/$CIRRUS_PR/head:pull/$CIRRUS_PR
   #   git reset --hard $CIRRUS_CHANGE_IN_REPO
  #  fi    

  SYNC_SCRIPT_script:
      - curl -sL https://raw.githubusercontent.com/SatoruGojo2k23/ROMBuilder-CI/main/scripts/sync_rom.sh | bash
      
  BUILD_SCRIPT_script:
      - curl -sL https://raw.githubusercontent.com/SatoruGojo2k23/ROMBuilder-CI/main/scripts/build_rom.sh | bash
      
  UPLOAD_SCRIPT_script:
      - curl -sL https://raw.githubusercontent.com/SatoruGojo2k23/ROMBuilder-CI/main/scripts/upload_rom.sh | bash
